name: Verify order placement scenario 2
on:
  workflow_dispatch:  # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Tests
        run: npm run test:qa:orderplacement:safari
        continue-on-error: true

      - name: Generate Allure Report
        run: |
          npx allure generate allure-results --clean -o allure-report
        continue-on-error: true

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full history to prevent conflicts

      - name: Restore Previous Allure History
        uses: actions/cache@v3
        with:
          path: allure-history
          key: allure-history-${{ github.run_id }}
          restore-keys: allure-history-

      - name: Move Reports for History
        run: |
          mkdir -p allure-history
          cp -r allure-report/* allure-history/ || true

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
          keep_files: true
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
